Final testing
Kingstalux/Webpack pull request #9
Opened 2021-10-07 15:50 UTC by Ugboaja-Uchechi

Use jest framework

Create a test folder for a file(s) containing the following functions:
  a function for editing the task description.
  a function for updating an item's 'completed' status.
  the "Clear all completed" function.

2021-10-07 15:56 UTC, Ugboaja-Uchechi commented
All linters have passed.

2021-10-07 16:17 UTC, rukundoeric requested changes
Hi @Kingstalux, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-07 16:17 UTC, rukundoeric commented on src/_tests_/edit.test.js
> +import editItem from '../_mocks_/edit.js';
- [ ] <b>REQUIRED:</b> Here, you are supposed to test the real functions with mocked data.  which means that the `editItem` function should be imported from `script2.js`. and then use mocked data. Check out this [Article](https://bholmes.dev/blog/mocking-browser-apis-fetch-localstorage-dates-the-easy-way-with-jest/) if you wanted to learn more on how to mock data in localStorage.

2021-10-07 16:17 UTC, rukundoeric commented on src/_tests_/remove.test.js
>  import removeItem from '../_mocks_/remove.js';
- [ ] <b>REQUIRED:</b> The same here, you are supposed to test the real functions with mocked data.  which means that the `removeItem` function should be imported from `script2.js`. and then use mocked data. Check out this [Article](https://bholmes.dev/blog/mocking-browser-apis-fetch-localstorage-dates-the-easy-way-with-jest/) if you wanted to learn more on how to mock data in localStorage.

2021-10-07 16:17 UTC, rukundoeric commented on src/_tests_/status.test.js
> +import status from '../_mocks_/status.js';
- [ ] <b>REQUIRED:</b> The same here, you are supposed to test the real functions with mocked data.  which means that the `changeStatus` function should be imported from `script2.js`. and then use mocked data. Check out this [Article](https://bholmes.dev/blog/mocking-browser-apis-fetch-localstorage-dates-the-easy-way-with-jest/) if you wanted to learn more on how to mock data in localStorage.

2021-10-07 17:41 UTC, Ugboaja-Uchechi commented on src/_tests_/edit.test.js
> +import editItem from '../_mocks_/edit.js';
HI, my partner and I are a bit lost on the changes you requested, if you don't mind, can you join us on a zoom call

2021-10-08 07:56 UTC, Ugboaja-Uchechi commented
My partners and I are testing the real functions but we copied those functions into individual files since we have to use mock data.
This is the same thing we did for the first testing project and it was approved.

2021-10-08 07:59 UTC, AshakaE approved these changes
### Hi @Ugboaja-Uchechi  🙋‍♀️, 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-08 08:07 UTC, merged